// Automatically generated. Do not edit.

/// Automatically generated API for [CloudKit](https://developer.apple.com/documentation/cloudkit?language=objc).
///
/// Generated with [cupertino_ffi](https://pub.dev/packages/cupertino_ffi).
library cupertino_ffi.cloudkit;

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:meta/meta.dart';
import 'package:cupertino_ffi/objc.dart' show ObjcMethodInfo;
import 'package:cupertino_ffi/objc.dart' as _objc;
import 'package:cupertino_ffi/src/generated/internal.dart' as _objc_call;
export 'package:cupertino_ffi/core_foundation.dart'
    show arcPush, arcPop, arcReturn, arcFieldGet, arcFieldSet;

part 'src/generated/cloudkit/CKAcceptSharesOperation.dart';
part 'src/generated/cloudkit/CKAcceptSharesOperationInfo.dart';
part 'src/generated/cloudkit/CKAccountInfo.dart';
part 'src/generated/cloudkit/CKAccountOverrideInfo.dart';
part 'src/generated/cloudkit/CKAggregateExpressionValidator.dart';
part 'src/generated/cloudkit/CKAggregateZonePCSOperation.dart';
part 'src/generated/cloudkit/CKAggregateZonePCSOperationInfo.dart';
part 'src/generated/cloudkit/CKAllPredicateValidator.dart';
part 'src/generated/cloudkit/CKAnyPredicateValidator.dart';
part 'src/generated/cloudkit/CKApplicationPermissionGroup.dart';
part 'src/generated/cloudkit/CKArchiveRecordsOperation.dart';
part 'src/generated/cloudkit/CKArchiveRecordsOperationInfo.dart';
part 'src/generated/cloudkit/CKArchivedAnchoredPackage.dart';
part 'src/generated/cloudkit/CKAsset.dart';
part 'src/generated/cloudkit/CKAssetCopyInfo.dart';
part 'src/generated/cloudkit/CKAssetDownloadPreauthorization.dart';
part 'src/generated/cloudkit/CKAssetReference.dart';
part 'src/generated/cloudkit/CKAssetRereferenceInfo.dart';
part 'src/generated/cloudkit/CKAssetTransferOptions.dart';
part 'src/generated/cloudkit/CKAutoBugCaptureMetadata.dart';
part 'src/generated/cloudkit/CKBehaviorOptions.dart';
part 'src/generated/cloudkit/CKBlockingAsyncQueue.dart';
part 'src/generated/cloudkit/CKCodeFunctionInvokeOperation.dart';
part 'src/generated/cloudkit/CKCodeFunctionInvokeOperationInfo.dart';
part 'src/generated/cloudkit/CKComparisonModifierValidator.dart';
part 'src/generated/cloudkit/CKComparisonOperatorValidator.dart';
part 'src/generated/cloudkit/CKComparisonOptionsValidator.dart';
part 'src/generated/cloudkit/CKComparisonPredicateValidator.dart';
part 'src/generated/cloudkit/CKCompleteParticipantVettingOperation.dart';
part 'src/generated/cloudkit/CKCompleteParticipantVettingOperationInfo.dart';
part 'src/generated/cloudkit/CKCompoundSubpredicateValidator.dart';
part 'src/generated/cloudkit/CKCompoundTypePredicateValidator.dart';
part 'src/generated/cloudkit/CKConstantValueExpressionValidator.dart';
part 'src/generated/cloudkit/CKContactsSupport.dart';
part 'src/generated/cloudkit/CKContainer.dart';
part 'src/generated/cloudkit/CKContainerID.dart';
part 'src/generated/cloudkit/CKContainerOptions.dart';
part 'src/generated/cloudkit/CKContainerSetupInfo.dart';
part 'src/generated/cloudkit/CKContainerXPCProxy.dart';
part 'src/generated/cloudkit/CKCustomBlockValidator.dart';
part 'src/generated/cloudkit/CKDCancelToken.dart';
part 'src/generated/cloudkit/CKDPDate.dart';
part 'src/generated/cloudkit/CKDPIdentifier.dart';
part 'src/generated/cloudkit/CKDPLocationCoordinate.dart';
part 'src/generated/cloudkit/CKDPRecordFieldValueEncryptedValue.dart';
part 'src/generated/cloudkit/CKDPRecordIdentifier.dart';
part 'src/generated/cloudkit/CKDPRecordReference.dart';
part 'src/generated/cloudkit/CKDPRecordZoneIdentifier.dart';
part 'src/generated/cloudkit/CKDatabase.dart';
part 'src/generated/cloudkit/CKDatabaseNotification.dart';
part 'src/generated/cloudkit/CKDatabaseOperation.dart';
part 'src/generated/cloudkit/CKDatabaseOperationInfo.dart';
part 'src/generated/cloudkit/CKDatabaseSubscription.dart';
part 'src/generated/cloudkit/CKDeclarativePredicateValidator.dart';
part 'src/generated/cloudkit/CKDiscoverAllContactsOperation.dart';
part 'src/generated/cloudkit/CKDiscoverAllUserIdentitiesOperation.dart';
part 'src/generated/cloudkit/CKDiscoverUserIdentitiesOperation.dart';
part 'src/generated/cloudkit/CKDiscoverUserIdentitiesOperationInfo.dart';
part 'src/generated/cloudkit/CKDiscoverUserInfosOperation.dart';
part 'src/generated/cloudkit/CKDiscoveredUserInfo.dart';
part 'src/generated/cloudkit/CKEncryptedData.dart';
part 'src/generated/cloudkit/CKEncryptedDate.dart';
part 'src/generated/cloudkit/CKEncryptedDateArray.dart';
part 'src/generated/cloudkit/CKEncryptedDouble.dart';
part 'src/generated/cloudkit/CKEncryptedDoubleArray.dart';
part 'src/generated/cloudkit/CKEncryptedEmptyArray.dart';
part 'src/generated/cloudkit/CKEncryptedLocation.dart';
part 'src/generated/cloudkit/CKEncryptedLocationArray.dart';
part 'src/generated/cloudkit/CKEncryptedLongLong.dart';
part 'src/generated/cloudkit/CKEncryptedLongLongArray.dart';
part 'src/generated/cloudkit/CKEncryptedRecordValueStore.dart';
part 'src/generated/cloudkit/CKEncryptedReference.dart';
part 'src/generated/cloudkit/CKEncryptedString.dart';
part 'src/generated/cloudkit/CKEncryptedStringArray.dart';
part 'src/generated/cloudkit/CKEvaluatedObjectExpressionValidator.dart';
part 'src/generated/cloudkit/CKEventMetric.dart';
part 'src/generated/cloudkit/CKEventMetricInfo.dart';
part 'src/generated/cloudkit/CKEventOperationGroupInfo.dart';
part 'src/generated/cloudkit/CKEventOperationInfo.dart';
part 'src/generated/cloudkit/CKException.dart';
part 'src/generated/cloudkit/CKFetchArchivedRecordsOperation.dart';
part 'src/generated/cloudkit/CKFetchArchivedRecordsOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchArchivedRecordsOptions.dart';
part 'src/generated/cloudkit/CKFetchDatabaseChangesOperation.dart';
part 'src/generated/cloudkit/CKFetchDatabaseChangesOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchDatabaseChangesOperationResult.dart';
part 'src/generated/cloudkit/CKFetchNotificationChangesOperation.dart';
part 'src/generated/cloudkit/CKFetchNotificationChangesOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchNotificationChangesOperationResult.dart';
part 'src/generated/cloudkit/CKFetchRecordChangesOperation.dart';
part 'src/generated/cloudkit/CKFetchRecordChangesOperationResult.dart';
part 'src/generated/cloudkit/CKFetchRecordVersionsOperation.dart';
part 'src/generated/cloudkit/CKFetchRecordVersionsOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchRecordZoneChangesConfiguration.dart';
part 'src/generated/cloudkit/CKFetchRecordZoneChangesOperation.dart';
part 'src/generated/cloudkit/CKFetchRecordZoneChangesOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchRecordZoneChangesOptions.dart';
part 'src/generated/cloudkit/CKFetchRecordZonesOperation.dart';
part 'src/generated/cloudkit/CKFetchRecordZonesOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchRecordsAssetInfo.dart';
part 'src/generated/cloudkit/CKFetchRecordsOperation.dart';
part 'src/generated/cloudkit/CKFetchRecordsOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchShareMetadataOperation.dart';
part 'src/generated/cloudkit/CKFetchShareMetadataOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchShareParticipantKeyOperation.dart';
part 'src/generated/cloudkit/CKFetchShareParticipantKeyOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchShareParticipantsOperation.dart';
part 'src/generated/cloudkit/CKFetchShareParticipantsOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchSubscriptionsOperation.dart';
part 'src/generated/cloudkit/CKFetchSubscriptionsOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchUserQuotaOperation.dart';
part 'src/generated/cloudkit/CKFetchUserQuotaOperationResult.dart';
part 'src/generated/cloudkit/CKFetchWebAuthTokenOperation.dart';
part 'src/generated/cloudkit/CKFetchWebAuthTokenOperationInfo.dart';
part 'src/generated/cloudkit/CKFetchWebAuthTokenOperationResult.dart';
part 'src/generated/cloudkit/CKFetchWhitelistedBundleIDsOperation.dart';
part 'src/generated/cloudkit/CKFetchWhitelistedBundleIDsOperationResult.dart';
part 'src/generated/cloudkit/CKFileMetadata.dart';
part 'src/generated/cloudkit/CKFileOpenInfo.dart';
part 'src/generated/cloudkit/CKFileOpenResult.dart';
part 'src/generated/cloudkit/CKFlipFlopPredicateValidator.dart';
part 'src/generated/cloudkit/CKFlowControl.dart';
part 'src/generated/cloudkit/CKFunctionExpressionValidator.dart';
part 'src/generated/cloudkit/CKInitiateParticipantVettingOperation.dart';
part 'src/generated/cloudkit/CKInitiateParticipantVettingOperationInfo.dart';
part 'src/generated/cloudkit/CKInternalError.dart';
part 'src/generated/cloudkit/CKKeyPathExpressionValidator.dart';
part 'src/generated/cloudkit/CKKindOfClassValidator.dart';
part 'src/generated/cloudkit/CKKindOfCollectionClassValidator.dart';
part 'src/generated/cloudkit/CKLegacyPredicateValidator.dart';
part 'src/generated/cloudkit/CKLocationSortDescriptor.dart';
part 'src/generated/cloudkit/CKLogFacilityWrapper.dart';
part 'src/generated/cloudkit/CKMarkNotificationsReadOperation.dart';
part 'src/generated/cloudkit/CKMarkNotificationsReadOperationInfo.dart';
part 'src/generated/cloudkit/CKMetric.dart';
part 'src/generated/cloudkit/CKModifyBadgeOperation.dart';
part 'src/generated/cloudkit/CKModifyBadgeOperationInfo.dart';
part 'src/generated/cloudkit/CKModifyRecordAccessOperation.dart';
part 'src/generated/cloudkit/CKModifyRecordAccessOperationInfo.dart';
part 'src/generated/cloudkit/CKModifyRecordZonesOperation.dart';
part 'src/generated/cloudkit/CKModifyRecordZonesOperationInfo.dart';
part 'src/generated/cloudkit/CKModifyRecordsOperation.dart';
part 'src/generated/cloudkit/CKModifyRecordsOperationInfo.dart';
part 'src/generated/cloudkit/CKModifySubscriptionsOperation.dart';
part 'src/generated/cloudkit/CKModifySubscriptionsOperationInfo.dart';
part 'src/generated/cloudkit/CKModifyWebSharingOperation.dart';
part 'src/generated/cloudkit/CKModifyWebSharingOperationInfo.dart';
part 'src/generated/cloudkit/CKNilValidator.dart';
part 'src/generated/cloudkit/CKNotification.dart';
part 'src/generated/cloudkit/CKNotificationID.dart';
part 'src/generated/cloudkit/CKNotificationInfo.dart';
part 'src/generated/cloudkit/CKObjCClass.dart';
part 'src/generated/cloudkit/CKObjCProperty.dart';
part 'src/generated/cloudkit/CKObjCType.dart';
part 'src/generated/cloudkit/CKObject.dart';
part 'src/generated/cloudkit/CKOperation.dart';
part 'src/generated/cloudkit/CKOperationCallbackManager.dart';
part 'src/generated/cloudkit/CKOperationConfiguration.dart';
part 'src/generated/cloudkit/CKOperationFlowControlInfo.dart';
part 'src/generated/cloudkit/CKOperationFlowControlManager.dart';
part 'src/generated/cloudkit/CKOperationGroup.dart';
part 'src/generated/cloudkit/CKOperationGroupSystemImposedInfo.dart';
part 'src/generated/cloudkit/CKOperationGroupSystemImposedInfoConfiguration.dart';
part 'src/generated/cloudkit/CKOperationInfo.dart';
part 'src/generated/cloudkit/CKOperationMMCSRequestOptions.dart';
part 'src/generated/cloudkit/CKOperationMetrics.dart';
part 'src/generated/cloudkit/CKOperationResult.dart';
part 'src/generated/cloudkit/CKPCSDiagnosticInformation.dart';
part 'src/generated/cloudkit/CKPackage.dart';
part 'src/generated/cloudkit/CKPackageDB.dart';
part 'src/generated/cloudkit/CKPackageDBDelegate.dart';
part 'src/generated/cloudkit/CKPackageItem.dart';
part 'src/generated/cloudkit/CKPackageSection.dart';
part 'src/generated/cloudkit/CKPlaceholderOperation.dart';
part 'src/generated/cloudkit/CKPredicateValidator.dart';
part 'src/generated/cloudkit/CKPredicateValidatorInstance.dart';
part 'src/generated/cloudkit/CKPrettyError.dart';
part 'src/generated/cloudkit/CKPublicKey.dart';
part 'src/generated/cloudkit/CKPublishAssetsOperation.dart';
part 'src/generated/cloudkit/CKPublishAssetsOperationInfo.dart';
part 'src/generated/cloudkit/CKQuery.dart';
part 'src/generated/cloudkit/CKQueryCursor.dart';
part 'src/generated/cloudkit/CKQueryNotification.dart';
part 'src/generated/cloudkit/CKQueryOperation.dart';
part 'src/generated/cloudkit/CKQueryOperationInfo.dart';
part 'src/generated/cloudkit/CKQueryOperationResult.dart';
part 'src/generated/cloudkit/CKQuerySubscription.dart';
part 'src/generated/cloudkit/CKRecord.dart';
part 'src/generated/cloudkit/CKRecordGraph.dart';
part 'src/generated/cloudkit/CKRecordGraphNode.dart';
part 'src/generated/cloudkit/CKRecordID.dart';
part 'src/generated/cloudkit/CKRecordValueStore.dart';
part 'src/generated/cloudkit/CKRecordZone.dart';
part 'src/generated/cloudkit/CKRecordZoneID.dart';
part 'src/generated/cloudkit/CKRecordZoneNotification.dart';
part 'src/generated/cloudkit/CKRecordZoneSubscription.dart';
part 'src/generated/cloudkit/CKRecursivePredicateValidator.dart';
part 'src/generated/cloudkit/CKReference.dart';
part 'src/generated/cloudkit/CKRepairZonePCSOperation.dart';
part 'src/generated/cloudkit/CKRepairZonePCSOperationInfo.dart';
part 'src/generated/cloudkit/CKRequestInfo.dart';
part 'src/generated/cloudkit/CKSQLite.dart';
part 'src/generated/cloudkit/CKSQLiteError.dart';
part 'src/generated/cloudkit/CKSQLitePool.dart';
part 'src/generated/cloudkit/CKSQLiteStatement.dart';
part 'src/generated/cloudkit/CKSQLiteStatementEnumerator.dart';
part 'src/generated/cloudkit/CKServerChangeToken.dart';
part 'src/generated/cloudkit/CKShare.dart';
part 'src/generated/cloudkit/CKShareMetadata.dart';
part 'src/generated/cloudkit/CKShareParticipant.dart';
part 'src/generated/cloudkit/CKSignatureGenerator.dart';
part 'src/generated/cloudkit/CKStringValueValidator.dart';
part 'src/generated/cloudkit/CKSubscription.dart';
part 'src/generated/cloudkit/CKTimeLogger.dart';
part 'src/generated/cloudkit/CKTimeLoggerLog.dart';
part 'src/generated/cloudkit/CKTimeLoggerLogPauseRecord.dart';
part 'src/generated/cloudkit/CKTruePredicateValidator.dart';
part 'src/generated/cloudkit/CKTrueValidator.dart';
part 'src/generated/cloudkit/CKUserIdentity.dart';
part 'src/generated/cloudkit/CKUserIdentityLookupInfo.dart';
part 'src/generated/cloudkit/CKUserNotificationUtilities.dart';
part 'src/generated/cloudkit/CKZonePCSDiagnosticInformation.dart';

bool _isDynamicLibraryOpened = false;

/// Ensures that the Objective-C library has been loaded by the process.
///
/// Otherwise Objective-C runtime can't find the classes.
void _ensureDynamicLibraryHasBeenOpened() {
  if (!_isDynamicLibraryOpened) {
    _isDynamicLibraryOpened = true;
    DynamicLibrary.open(
      "/System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit",
    );
  }
}
