// Automatically generated. Do not edit.

/// Automatically generated API for [SceneKit](https://developer.apple.com/documentation/scenekit?language=objc).
///
/// Generated with [cupertino_ffi](https://pub.dev/packages/cupertino_ffi).
library cupertino_ffi.scenekit;

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:meta/meta.dart';
import 'package:cupertino_ffi/objc.dart' show ObjcMethodInfo;
import 'package:cupertino_ffi/objc.dart' as _objc;
import 'package:cupertino_ffi/src/generated/internal.dart' as _objc_call;
export 'package:cupertino_ffi/core_foundation.dart'
    show arcPush, arcPop, arcReturn, arcFieldGet, arcFieldSet;

part 'src/generated/scenekit/C3DAnimationBinding.dart';
part 'src/generated/scenekit/C3DBinding.dart';
part 'src/generated/scenekit/C3DEngineNotificationQueueTransientWrapper.dart';
part 'src/generated/scenekit/C3DIONSZipFileArchive.dart';
part 'src/generated/scenekit/SCN3DConnexionDevice.dart';
part 'src/generated/scenekit/SCNAVPlayerSource.dart';
part 'src/generated/scenekit/SCNAccelerationConstraint.dart';
part 'src/generated/scenekit/SCNAction.dart';
part 'src/generated/scenekit/SCNActionCustom.dart';
part 'src/generated/scenekit/SCNActionFade.dart';
part 'src/generated/scenekit/SCNActionGroup.dart';
part 'src/generated/scenekit/SCNActionHide.dart';
part 'src/generated/scenekit/SCNActionJavaScript.dart';
part 'src/generated/scenekit/SCNActionMove.dart';
part 'src/generated/scenekit/SCNActionPerformSelector.dart';
part 'src/generated/scenekit/SCNActionPlaySound.dart';
part 'src/generated/scenekit/SCNActionReference.dart';
part 'src/generated/scenekit/SCNActionRemove.dart';
part 'src/generated/scenekit/SCNActionRepeat.dart';
part 'src/generated/scenekit/SCNActionRotate.dart';
part 'src/generated/scenekit/SCNActionRunAction.dart';
part 'src/generated/scenekit/SCNActionRunBlock.dart';
part 'src/generated/scenekit/SCNActionScale.dart';
part 'src/generated/scenekit/SCNActionSequence.dart';
part 'src/generated/scenekit/SCNActionTargetState.dart';
part 'src/generated/scenekit/SCNActionWait.dart';
part 'src/generated/scenekit/SCNAnimation.dart';
part 'src/generated/scenekit/SCNAnimationEvent.dart';
part 'src/generated/scenekit/SCNAnimationPlayer.dart';
part 'src/generated/scenekit/SCNAnimationReference.dart';
part 'src/generated/scenekit/SCNAssetCatalog.dart';
part 'src/generated/scenekit/SCNAssetCatalogCacheEntry.dart';
part 'src/generated/scenekit/SCNAudioPlayer.dart';
part 'src/generated/scenekit/SCNAudioSource.dart';
part 'src/generated/scenekit/SCNAuthoringEnvironment.dart';
part 'src/generated/scenekit/SCNAuthoringEnvironment2.dart';
part 'src/generated/scenekit/SCNAvoidOccluderConstraint.dart';
part 'src/generated/scenekit/SCNBackingLayer.dart';
part 'src/generated/scenekit/SCNBillboardConstraint.dart';
part 'src/generated/scenekit/SCNBoundingBox.dart';
part 'src/generated/scenekit/SCNBoundingSphere.dart';
part 'src/generated/scenekit/SCNBox.dart';
part 'src/generated/scenekit/SCNBufferBinding.dart';
part 'src/generated/scenekit/SCNCOLLADAExportOperation.dart';
part 'src/generated/scenekit/SCNCamera.dart';
part 'src/generated/scenekit/SCNCameraControlEventHandler.dart';
part 'src/generated/scenekit/SCNCameraController.dart';
part 'src/generated/scenekit/SCNCameraNavigationController.dart';
part 'src/generated/scenekit/SCNCapsule.dart';
part 'src/generated/scenekit/SCNCaptureDeviceOutputConsumerSource.dart';
part 'src/generated/scenekit/SCNCaptureDeviceSource.dart';
part 'src/generated/scenekit/SCNCommonProfileProgramCache.dart';
part 'src/generated/scenekit/SCNCommonProfileProgramGenerator.dart';
part 'src/generated/scenekit/SCNCommonProfileProgramGeneratorGL.dart';
part 'src/generated/scenekit/SCNCommonProfileProgramGeneratorMetal.dart';
part 'src/generated/scenekit/SCNCone.dart';
part 'src/generated/scenekit/SCNConstantScaleConstraint.dart';
part 'src/generated/scenekit/SCNConstraint.dart';
part 'src/generated/scenekit/SCNCylinder.dart';
part 'src/generated/scenekit/SCNDeferredProgramGeneratorMetal.dart';
part 'src/generated/scenekit/SCNDelegateSource.dart';
part 'src/generated/scenekit/SCNDisplayLink.dart';
part 'src/generated/scenekit/SCNDistanceConstraint.dart';
part 'src/generated/scenekit/SCNEventHandler.dart';
part 'src/generated/scenekit/SCNExportOperation.dart';
part 'src/generated/scenekit/SCNFixedSizePage.dart';
part 'src/generated/scenekit/SCNFloor.dart';
part 'src/generated/scenekit/SCNGeometry.dart';
part 'src/generated/scenekit/SCNGeometryElement.dart';
part 'src/generated/scenekit/SCNGeometrySource.dart';
part 'src/generated/scenekit/SCNGeometryTessellator.dart';
part 'src/generated/scenekit/SCNHitTestResult.dart';
part 'src/generated/scenekit/SCNIKConstraint.dart';
part 'src/generated/scenekit/SCNIKJoint.dart';
part 'src/generated/scenekit/SCNImageSource.dart';
part 'src/generated/scenekit/SCNJSImage.dart';
part 'src/generated/scenekit/SCNJSValue.dart';
part 'src/generated/scenekit/SCNJSValueTmpImp.dart';
part 'src/generated/scenekit/SCNJitterer.dart';
part 'src/generated/scenekit/SCNKeyedArchiver.dart';
part 'src/generated/scenekit/SCNKeyedUnarchiver.dart';
part 'src/generated/scenekit/SCNLayer.dart';
part 'src/generated/scenekit/SCNLayerSource.dart';
part 'src/generated/scenekit/SCNLevelOfDetail.dart';
part 'src/generated/scenekit/SCNLight.dart';
part 'src/generated/scenekit/SCNLookAtConstraint.dart';
part 'src/generated/scenekit/SCNLowLatencyMetalLayer.dart';
part 'src/generated/scenekit/SCNMTLArgumentBinder.dart';
part 'src/generated/scenekit/SCNMTLBuffer.dart';
part 'src/generated/scenekit/SCNMTLBufferAllocator.dart';
part 'src/generated/scenekit/SCNMTLBufferAllocatorSubBuffer.dart';
part 'src/generated/scenekit/SCNMTLComputePipeline.dart';
part 'src/generated/scenekit/SCNMTLLibrary.dart';
part 'src/generated/scenekit/SCNMTLLibraryManager.dart';
part 'src/generated/scenekit/SCNMTLMesh.dart';
part 'src/generated/scenekit/SCNMTLMeshElement.dart';
part 'src/generated/scenekit/SCNMTLMorph.dart';
part 'src/generated/scenekit/SCNMTLPassResourceBinding.dart';
part 'src/generated/scenekit/SCNMTLReduceDepthPass.dart';
part 'src/generated/scenekit/SCNMTLRenderContext.dart';
part 'src/generated/scenekit/SCNMTLRenderPass.dart';
part 'src/generated/scenekit/SCNMTLRenderPipeline.dart';
part 'src/generated/scenekit/SCNMTLResourceBinding.dart';
part 'src/generated/scenekit/SCNMTLResourceManager.dart';
part 'src/generated/scenekit/SCNMTLSemanticResourceBinding.dart';
part 'src/generated/scenekit/SCNMTLShadable.dart';
part 'src/generated/scenekit/SCNMTLShadableKey.dart';
part 'src/generated/scenekit/SCNMTLShaderBindingsGenerator.dart';
part 'src/generated/scenekit/SCNMTLSkin.dart';
part 'src/generated/scenekit/SCNMTLTessellator.dart';
part 'src/generated/scenekit/SCNManipulableItem.dart';
part 'src/generated/scenekit/SCNManipulator.dart';
part 'src/generated/scenekit/SCNMaterial.dart';
part 'src/generated/scenekit/SCNMaterialAttachment.dart';
part 'src/generated/scenekit/SCNMaterialProperty.dart';
part 'src/generated/scenekit/SCNMetalBackingLayer.dart';
part 'src/generated/scenekit/SCNMetalLayer.dart';
part 'src/generated/scenekit/SCNMetalWireframeResource.dart';
part 'src/generated/scenekit/SCNMonitor.dart';
part 'src/generated/scenekit/SCNMorpher.dart';
part 'src/generated/scenekit/SCNMovieExportOperation.dart';
part 'src/generated/scenekit/SCNMutableGeometry.dart';
part 'src/generated/scenekit/SCNMutableGeometrySource.dart';
part 'src/generated/scenekit/SCNNode.dart';
part 'src/generated/scenekit/SCNNodeComponent.dart';
part 'src/generated/scenekit/SCNNodeManipulableItem.dart';
part 'src/generated/scenekit/SCNNodeReference.dart';
part 'src/generated/scenekit/SCNNodeWeakComponent.dart';
part 'src/generated/scenekit/SCNOffscreenRenderer.dart';
part 'src/generated/scenekit/SCNOrderedDictionary.dart';
part 'src/generated/scenekit/SCNParticlePropertyController.dart';
part 'src/generated/scenekit/SCNParticleSystem.dart';
part 'src/generated/scenekit/SCNPass.dart';
part 'src/generated/scenekit/SCNPassContext.dart';
part 'src/generated/scenekit/SCNPhysicsBallSocketJoint.dart';
part 'src/generated/scenekit/SCNPhysicsBehavior.dart';
part 'src/generated/scenekit/SCNPhysicsBody.dart';
part 'src/generated/scenekit/SCNPhysicsCharacter.dart';
part 'src/generated/scenekit/SCNPhysicsConeTwistJoint.dart';
part 'src/generated/scenekit/SCNPhysicsContact.dart';
part 'src/generated/scenekit/SCNPhysicsCustomField.dart';
part 'src/generated/scenekit/SCNPhysicsDragField.dart';
part 'src/generated/scenekit/SCNPhysicsElectricField.dart';
part 'src/generated/scenekit/SCNPhysicsField.dart';
part 'src/generated/scenekit/SCNPhysicsHingeJoint.dart';
part 'src/generated/scenekit/SCNPhysicsLinearGravityField.dart';
part 'src/generated/scenekit/SCNPhysicsMagneticField.dart';
part 'src/generated/scenekit/SCNPhysicsNoiseField.dart';
part 'src/generated/scenekit/SCNPhysicsRadialGravityField.dart';
part 'src/generated/scenekit/SCNPhysicsShape.dart';
part 'src/generated/scenekit/SCNPhysicsSliderJoint.dart';
part 'src/generated/scenekit/SCNPhysicsSpringField.dart';
part 'src/generated/scenekit/SCNPhysicsTurbulenceField.dart';
part 'src/generated/scenekit/SCNPhysicsVehicle.dart';
part 'src/generated/scenekit/SCNPhysicsVehicleWheel.dart';
part 'src/generated/scenekit/SCNPhysicsVortexField.dart';
part 'src/generated/scenekit/SCNPhysicsWorld.dart';
part 'src/generated/scenekit/SCNPlane.dart';
part 'src/generated/scenekit/SCNPostProcessPass.dart';
part 'src/generated/scenekit/SCNProgram.dart';
part 'src/generated/scenekit/SCNProgramSemanticInfo.dart';
part 'src/generated/scenekit/SCNPyramid.dart';
part 'src/generated/scenekit/SCNRecursiveLock.dart';
part 'src/generated/scenekit/SCNReferenceNode.dart';
part 'src/generated/scenekit/SCNRenderTarget.dart';
part 'src/generated/scenekit/SCNRenderTargetRegistry.dart';
part 'src/generated/scenekit/SCNRenderTargetView.dart';
part 'src/generated/scenekit/SCNRenderer.dart';
part 'src/generated/scenekit/SCNRendererOptionsPanel.dart';
part 'src/generated/scenekit/SCNRendererOptionsPanelController.dart';
part 'src/generated/scenekit/SCNRendererTransitionContext.dart';
part 'src/generated/scenekit/SCNRendererViewPoint.dart';
part 'src/generated/scenekit/SCNReplicatorConstraint.dart';
part 'src/generated/scenekit/SCNSSAOPass.dart';
part 'src/generated/scenekit/SCNScene.dart';
part 'src/generated/scenekit/SCNSceneDatabase.dart';
part 'src/generated/scenekit/SCNSceneLookUpUnarchiver.dart';
part 'src/generated/scenekit/SCNSceneSource.dart';
part 'src/generated/scenekit/SCNShadableHelper.dart';
part 'src/generated/scenekit/SCNShape.dart';
part 'src/generated/scenekit/SCNSkinner.dart';
part 'src/generated/scenekit/SCNSliderConstraint.dart';
part 'src/generated/scenekit/SCNSourceRendererRegistry.dart';
part 'src/generated/scenekit/SCNSphere.dart';
part 'src/generated/scenekit/SCNSpriteKitEventHandler.dart';
part 'src/generated/scenekit/SCNSpriteKitSource.dart';
part 'src/generated/scenekit/SCNStatisticsProvider.dart';
part 'src/generated/scenekit/SCNTechnique.dart';
part 'src/generated/scenekit/SCNTechniquePanel.dart';
part 'src/generated/scenekit/SCNTechniquePanelController.dart';
part 'src/generated/scenekit/SCNText.dart';
part 'src/generated/scenekit/SCNTextureDelegateSource.dart';
part 'src/generated/scenekit/SCNTextureLayerSource.dart';
part 'src/generated/scenekit/SCNTextureOffscreenRenderingSource.dart';
part 'src/generated/scenekit/SCNTextureSource.dart';
part 'src/generated/scenekit/SCNTextureSpriteKitSource.dart';
part 'src/generated/scenekit/SCNTimingFunction.dart';
part 'src/generated/scenekit/SCNTorus.dart';
part 'src/generated/scenekit/SCNTransaction.dart';
part 'src/generated/scenekit/SCNTransformConstraint.dart';
part 'src/generated/scenekit/SCNTube.dart';
part 'src/generated/scenekit/SCNTypeInspector.dart';
part 'src/generated/scenekit/SCNUIArrayEditor.dart';
part 'src/generated/scenekit/SCNUIArrayEditorController.dart';
part 'src/generated/scenekit/SCNUIBindableView.dart';
part 'src/generated/scenekit/SCNUIColorWell.dart';
part 'src/generated/scenekit/SCNUID_ConstantTransformer.dart';
part 'src/generated/scenekit/SCNUID_NumberTransformer.dart';
part 'src/generated/scenekit/SCNUIDynamicInspector.dart';
part 'src/generated/scenekit/SCNUIDynamicInspectorConfiguration.dart';
part 'src/generated/scenekit/SCNUIHandleButton.dart';
part 'src/generated/scenekit/SCNUIImagePicker.dart';
part 'src/generated/scenekit/SCNUIMatrix4TextField.dart';
part 'src/generated/scenekit/SCNUIPopUpButton.dart';
part 'src/generated/scenekit/SCNUIProperty.dart';
part 'src/generated/scenekit/SCNUISceneGraphView.dart';
part 'src/generated/scenekit/SCNUIScrubber.dart';
part 'src/generated/scenekit/SCNUIScrubberCell.dart';
part 'src/generated/scenekit/SCNUIVector2TextField.dart';
part 'src/generated/scenekit/SCNUIVector3TextField.dart';
part 'src/generated/scenekit/SCNUIVector4TextField.dart';
part 'src/generated/scenekit/SCNView.dart';
part 'src/generated/scenekit/SCNWeakPointer.dart';
part 'src/generated/scenekit/SCN_CAKeyframeAnimation.dart';
part 'src/generated/scenekit/SCN_NSImageFromParticleImage.dart';
part 'src/generated/scenekit/SCN_NSImageFromSlotContents.dart';

bool _isDynamicLibraryOpened = false;

/// Ensures that the Objective-C library has been loaded by the process.
///
/// Otherwise Objective-C runtime can't find the classes.
void _ensureDynamicLibraryHasBeenOpened() {
  if (!_isDynamicLibraryOpened) {
    _isDynamicLibraryOpened = true;
    DynamicLibrary.open(
      "/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit",
    );
  }
}
